version: '2'
services:
 db:
  restart: always
  image: bsilvr/postgres-es
  container_name: postgres-iam
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=es-test
   - POSTGRES_DB=usermanagement
   - POSTGRES_USER=es

 flask:
  restart: always
  build: .
  container_name: es-apache-iam
  depends_on:
    - db
  ports:
    - "80:80"
